# Generated by Django 5.0.1 on 2024-02-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_product_seller_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='description',
        ),
    ]
